import express from 'express';
import multer from 'multer';
import { WebSocketServer, WebSocket } from 'ws';
import http from 'http';
import path from 'path';
import fs from 'fs';

import { JobQueue } from './job-queue.js';
import { JsonRpcRouter, RPC_ERRORS } from './jsonrpc.js';
import type { JsonRpcRequest, JsonRpcResponse } from './jsonrpc.js';
import { registerMethods } from './rpc-methods.js';
import { OLLAMA_DEFAULT_URL, DEFAULT_MODEL, DEFAULT_PORT, DEFAULT_API_KEY, DEFAULT_LLM_PROVIDER, UPLOAD_ONLY } from '../utils/constants.js';
import type { TranslationJob } from '../types.js';

// Storage config
const uploadDir = JobQueue.getUploadDir();
const storage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, uploadDir),
  filename: (_req, file, cb) => {
    const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
    const ext = path.extname(file.originalname);
    cb(null, `${uniqueSuffix}${ext}`);
  },
});
const upload = multer({
  storage,
  fileFilter: (_req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    if (ext === '.epub' || ext === '.fb2') {
      cb(null, true);
    } else {
      cb(new Error('Only .epub and .fb2 files are allowed'));
    }
  },
  limits: { fileSize: 100 * 1024 * 1024 }, // 100 MB
});

// WebSocket clients
interface WSClient {
  ws: WebSocket;
  jobId?: string;
}
const wsClients: Set<WSClient> = new Set();

/**
 * Create and configure the Express app + WebSocket server + JSON-RPC router.
 */
export function createApp(options?: { ollamaUrl?: string; defaultModel?: string; apiKey?: string; provider?: string; dbPath?: string }): {
  app: express.Application;
  server: http.Server;
  jobQueue: JobQueue;
  router: JsonRpcRouter;
} {
  const app = express();
  const server = http.createServer(app);
  const ollamaUrl = options?.ollamaUrl || OLLAMA_DEFAULT_URL;
  const defaultModel = options?.defaultModel || DEFAULT_MODEL;
  const apiKey = options?.apiKey || DEFAULT_API_KEY;
  const provider = options?.provider || DEFAULT_LLM_PROVIDER;
  const dbPath = options?.dbPath;

  // Job queue with WebSocket broadcast
  const jobQueue = new JobQueue((job) => {
    broadcastJobUpdate(job);
  });

  // JSON-RPC router
  const router = new JsonRpcRouter();
  registerMethods(router, { jobQueue, ollamaUrl, defaultModel, apiKey, provider, dbPath });

  // WebSocket server
  const wss = new WebSocketServer({ server, path: '/ws' });
  wss.on('connection', (ws) => {
    const client: WSClient = { ws };
    wsClients.add(client);

    ws.on('message', (data) => {
      try {
        const msg = JSON.parse(data.toString());
        // JSON-RPC over WebSocket
        if (msg.jsonrpc === '2.0' && msg.method) {
          router.handle(msg as JsonRpcRequest, { file: undefined, res: undefined }).then((response) => {
            // Don't send file download markers over WS
            if (response && (response as any).result?.__fileDownload) return;
            ws.send(JSON.stringify(response));
          });
          return;
        }
        // Legacy subscribe messages (backward compat)
        if (msg.type === 'subscribe' && msg.jobId) {
          client.jobId = msg.jobId;
          const job = jobQueue.get(msg.jobId);
          if (job) {
            ws.send(JSON.stringify({ type: 'job:update', job: serializeJob(job) }));
          }
        }
      } catch {
        // Ignore malformed messages
      }
    });

    ws.on('close', () => {
      wsClients.delete(client);
    });

    // Send list of recent jobs on connect
    const recentJobs = jobQueue.list().slice(0, 10).map(serializeJob);
    ws.send(JSON.stringify({ type: 'jobs:list', jobs: recentJobs }));
  });

  function broadcastJobUpdate(job: TranslationJob): void {
    const payload = JSON.stringify({ type: 'job:update', job: serializeJob(job) });
    for (const client of wsClients) {
      if (client.ws.readyState === WebSocket.OPEN) {
        if (!client.jobId || client.jobId === job.id) {
          client.ws.send(payload);
        }
      }
    }
  }

  // Middleware
  app.use(express.json());

  // ─── Export download endpoint (BEFORE static — avoid being swallowed) ──

  /**
   * GET /exports/:filename — Download an exported EPUB file.
   * Files are generated by book.export and stored in the output directory.
   */
  app.get('/exports/:filename', async (req, res): Promise<void> => {
    const outputDir = JobQueue.getOutputDir();
    const filePath = path.resolve(path.join(outputDir, req.params.filename));

    // Security: prevent directory traversal — resolved path must be inside outputDir
    if (!filePath.startsWith(path.resolve(outputDir) + path.sep) && filePath !== path.resolve(outputDir)) {
      res.status(403).json({ error: 'Forbidden' });
      return;
    }

    if (!fs.existsSync(filePath)) {
      res.status(404).json({ error: 'Export file not found' });
      return;
    }

    const stat = fs.statSync(filePath);
    res.setHeader('Content-Type', 'application/octet-stream');
    res.setHeader('Content-Length', stat.size);
    res.setHeader('Content-Disposition', `attachment; filename="${req.params.filename}"`);
    const fileStream = fs.createReadStream(filePath);
    fileStream.on('error', (err) => {
      console.error('Export stream error:', err);
      if (!res.headersSent) {
        res.status(500).json({ error: 'Stream error' });
      } else {
        res.end();
      }
    });
    fileStream.pipe(res);
  });

  // ─── File serving endpoint ───────────────────────────────────

  /**
   * GET /files/:id — Serve a binary image from the files table.
   * Used by book detail pages and assembled EPUBs to resolve file:ID references.
   */
  app.get('/files/:id', async (req, res): Promise<void> => {
    const { TranslateDb } = await import('../db/database.js');
    const db = new TranslateDb(dbPath);
    try {
      const file = db.getFile(req.params.id);
      if (!file) {
        res.status(404).json({ error: 'File not found' });
        return;
      }
      res.setHeader('Content-Type', file.mimeType);
      res.setHeader('Cache-Control', 'public, max-age=31536000, immutable'); // content-addressed — never changes
      res.setHeader('Content-Length', file.data.length);
      res.send(file.data);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    } finally {
      db.close();
    }
  });

  app.use(express.static(path.join(import.meta.dirname, 'public')));

  // ─── JSON-RPC endpoint ─────────────────────────────────────────

  /**
   * POST /rpc — JSON-RPC 2.0 endpoint.
   *
   * Supports two modes:
   * 1. JSON body: { jsonrpc: "2.0", method: "...", params: {...}, id: 1 }
   * 2. Multipart form: file upload + rpc field with JSON-RPC request
   */
  app.post('/rpc', upload.single('file'), async (req, res): Promise<void> => {
    let rpcRequest: JsonRpcRequest;

    // Parse the RPC request from either JSON body or form field
    if (req.is('multipart/form-data') && req.body?.rpc) {
      // Multipart: rpc field contains the JSON-RPC request
      try {
        rpcRequest = JSON.parse(req.body.rpc);
      } catch {
        res.json({
          jsonrpc: '2.0',
          error: RPC_ERRORS.PARSE_ERROR,
          id: null,
        });
        return;
      }
    } else if (req.is('application/json') && req.body?.jsonrpc) {
      // Pure JSON body
      rpcRequest = req.body;
    } else if (req.is('multipart/form-data') && req.body?.method) {
      // Multipart without explicit rpc field — build request from form fields
      rpcRequest = {
        jsonrpc: '2.0',
        method: req.body.method || 'book.upload',
        params: { ...req.body } as Record<string, any>,
        id: req.body.id || Date.now(),
      };
      const p = rpcRequest.params!;
      delete p.method;
      delete p.rpc;
    } else {
      res.json({
        jsonrpc: '2.0',
        error: RPC_ERRORS.INVALID_REQUEST,
        id: null,
      });
      return;
    }

    // Build context with uploaded file
    const context = { file: req.file, res };

    try {
      const response = await router.handle(rpcRequest, context);

      // Special handling for file downloads
      if ((response as any).result?.__fileDownload) {
        // res.download() already called by the handler
        return;
      }

      res.json(response);
    } catch (err: any) {
      res.json({
        jsonrpc: '2.0',
        error: { code: RPC_ERRORS.INTERNAL_ERROR.code, message: err.message },
        id: rpcRequest.id || null,
      });
    }
  });

  // ─── Legacy REST routes (redirect to RPC docs) ────────────────

  // GET / — serve web UI
  // (handled by express.static above)

  return { app, server, jobQueue, router };
}

/**
 * Start the web server.
 */
export function startServer(port: number = DEFAULT_PORT, options?: { ollamaUrl?: string; defaultModel?: string; apiKey?: string; provider?: string }): http.Server {
  const { server, jobQueue } = createApp(options);

  server.listen(port, () => {
    console.log(`🌐 ai-translate web server running at http://localhost:${port}`);
    console.log(`   JSON-RPC: http://localhost:${port}/rpc`);
    if (UPLOAD_ONLY) {
      console.log(`   Mode: UPLOAD_ONLY — books are parsed but not translated`);
    }
    console.log(`   WebSocket: ws://localhost:${port}/ws`);
  });

  // Cleanup old jobs every hour
  setInterval(() => {
    jobQueue.cleanup();
  }, 60 * 60 * 1000);

  return server;
}

/**
 * Serialize a TranslationJob for JSON transport.
 */
function serializeJob(job: TranslationJob): object {
  return {
    ...job,
    createdAt: job.createdAt.toISOString(),
    finishedAt: job.finishedAt?.toISOString() || null,
  };
}