import { Model, DataTypes, sql } from '@sequelize/core';
import type { InferAttributes, InferCreationAttributes, CreationOptional } from '@sequelize/core';
import { Attribute, Table } from '@sequelize/core/decorators-legacy';

/**
 * Sequelize model for the `tasks` table — async PDF OCR work, one task per page.
 *
 * `id` is a random UUID v4 (generated by the application, not deterministic).
 * Unlike the other tables, tasks carry both `createdAt` and `updatedAt`; both
 * are managed explicitly (timestamps: false) to mirror the original SQL.
 */
@Table({
  tableName: 'tasks',
  timestamps: false,
  underscored: true,
})
export class Task extends Model<InferAttributes<Task>, InferCreationAttributes<Task>> {
  @Attribute({ type: DataTypes.TEXT, primaryKey: true, allowNull: false })
  declare id: string;

  @Attribute({ type: DataTypes.TEXT, allowNull: false })
  declare docId: string;

  @Attribute({ type: DataTypes.TEXT, allowNull: false, defaultValue: 'ocr_page' })
  declare type: CreationOptional<string>;

  @Attribute({ type: DataTypes.INTEGER, allowNull: true })
  declare pageNum: CreationOptional<number | null>;

  @Attribute({ type: DataTypes.INTEGER, allowNull: true })
  declare totalPages: CreationOptional<number | null>;

  @Attribute({ type: DataTypes.TEXT, allowNull: false, defaultValue: 'pending' })
  declare status: CreationOptional<string>;

  @Attribute({ type: DataTypes.TEXT, allowNull: true })
  declare content: CreationOptional<string | null>;

  @Attribute({ type: DataTypes.TEXT, allowNull: true })
  declare error: CreationOptional<string | null>;

  @Attribute({ type: DataTypes.DATE, allowNull: false, defaultValue: sql.fn('now') })
  declare createdAt: CreationOptional<Date>;

  @Attribute({ type: DataTypes.DATE, allowNull: false, defaultValue: sql.fn('now') })
  declare updatedAt: CreationOptional<Date>;

  @Attribute({ type: DataTypes.DATE, allowNull: true })
  declare completedAt: CreationOptional<Date | null>;
}